[package]
name = "polodb"
version = "0.1.0"
authors = ["Vincent Chan <okcdz@diverse.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
