[package]
name = "polodb"
version = "2.0.0"
authors = ["Vincent Chan <okcdz@diverse.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polodb_core = { path = "../polodb_core" }
clap = "2.33.3"
chrono = "0.4"
