[package]
name = "polodb_core"
version = "0.0.1"
authors = ["Vincent Chan <okcdz@diverse.space>"]
edition = "2018"

[lib]
name="polodb_core"
path="lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
